"""add image name column

Revision ID: 1a2533327623
Revises: c1c8f7c32851
Create Date: 2022-03-15 15:50:52.371863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2533327623'
down_revision = 'c1c8f7c32851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_clubs', sa.Column('image_name', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('image_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'image_name')
    op.drop_column('book_clubs', 'image_name')
    # ### end Alembic commands ###
