"""create book club members

Revision ID: faafc8b776aa
Revises: 3205e55aa907
Create Date: 2022-02-13 14:34:13.078170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faafc8b776aa'
down_revision = '3205e55aa907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_clubs_members',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('book_club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_club_id'], ['book_clubs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'book_club_id', 'user_id'),
    sa.UniqueConstraint('book_club_id', 'user_id', name='book_club_member')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_clubs_members')
    # ### end Alembic commands ###
